apiVersion: v1
kind: Service
metadata:
  name: celora-web
  labels:
    app: celora-web
spec:
  selector:
    app: celora-web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  type: ClusterIP
