apiVersion: apps/v1
kind: Deployment
metadata:
  name: celora-web
  labels:
    app: celora-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: celora-web
  template:
    metadata:
      labels:
        app: celora-web
    spec:
      containers:
        - name: web
          image: ghcr.io/celora/placeholder:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PLATFORM_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: celora-platform-secrets
                  key: PLATFORM_API_BASE_URL
          readinessProbe:
            httpGet:
              path: /api/health/security
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health/security
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
      imagePullSecrets:
        - name: acr-pull-secret
